### ISSUE TITLE
Notification: about listing on webui extension index

### ISSUE THREAD

**Issue by w-e-w** [altoiddealer/--sd-webui-ar-plusplus#2]
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/330
@altoiddealer 
we recived a request to add this extentons to the index
when possible we like to confirm with the author before listing it
- are you okay with listing your extension on the index, if not then it won't be listed
- do have any changes you wish to make to the how it's listed (ie description)

if we didn't receive a confirmation with you after a week you will add it to index in this state
should you see this message at a later date and wish to make changes or have it removed please make contact.

```json
{
    "name": "Aspect Ratio and Resolution Buttons (ar-plusplus)",
    "url": "https://github.com/altoiddealer/--sd-webui-ar-plusplus.git",
    "description": "Fork of Aspect Ratio selector plus with advance resolution rounding",
    "tags": [
        "UI related"
    ]
}
```

**Comment by altoiddealer** [comment]
Thanks, yes, please include it in the index.  I am suggesting the following description, but the current also has my approval:

Fork of Aspect Ratio selector plus with optimal resolution calculation and rounding

**Comment by w-e-w** [comment]
nice

Updated to
```
Fork of Aspect Ratio selector plus with optimal resolution calculation and rounding
```
and merged

**Comment by altoiddealer** [comment]
> * [sd webui ar plusplus AUTOMATIC1111/stable-diffusion-webui-extensions#330](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/330)
>   @altoiddealer
>   we recived a request to add this extentons to the index
>   when possible we like to confirm with the author before listing it
> * are you okay with listing your extension on the index, if not then it won't be listed
> * do have any changes you wish to make to the how it's listed (ie description)
> 
> if we didn't receive a confirmation with you after a week you will add it to index in this state should you see this message at a later date and wish to make changes or have it removed please make contact.
> 
> ```json
> {
>     "name": "Aspect Ratio and Resolution Buttons (ar-plusplus)",
>     "url": "https://github.com/altoiddealer/--sd-webui-ar-plusplus.git",
>     "description": "Fork of Aspect Ratio selector plus with advance resolution rounding",
>     "tags": [
>         "UI related"
>     ]
> }
> ```

Maybe you've already seen this suggestion...

I had made a suggestion in the "Issues" for this extension to be integrated.  Really, I don't care that it's "my extension" (I merely added features to the original project), I just believe that it's essential to make desirable resolutions immediately accessible to users.

Stable Swarm comes stock with an aspect ratio selection dropdown, which result in the same wdith/height resolutions that this extension delivers.  mcmonkey actually responded to an inquiry I made in the SAI Discord, pointing me to their calculations in the Stable Swarm code.

AUTOMATIC1111/stable-diffusion-webui#15475

**Comment by w-e-w** [comment]
- reply https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15475#issuecomment-2185410414
