### ISSUE TITLE
Second Row Of Buttons dont have Text on them

### ISSUE THREAD

**Issue by a3nima** [altoiddealer/--sd-webui-ar-plusplus#3]
![grafik](https://github.com/user-attachments/assets/9a63bc7c-4bd3-4148-858a-3ba04e00831c)
 
in Forge, newest version. ( f2.0.1v1.10.1-previous-370-g0252ad86 )

Buttons are working though.

**Comment by altoiddealer** [comment]
The author of [--sd-webui-ar-plus](https://github.com/LEv145/--sd-webui-ar-plus), [LEv145](https://github.com/LEv145), was able to figure out a solution to the issues - see [this comment here](https://github.com/LEv145/--sd-webui-ar-plus/issues/24#issuecomment-2302119418).

I was able to adapt my fork to use their solution, which I just published now :)
